// src/angular-ji-tele-health/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-ji-tele-health';
}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/src/favicon.ico">

    <title>Starter Template for Bootstrap</title>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">
            <a class="nav-link" [routerLink]="['/home']">Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">

      <div class="starter-template">
        <router-outlet></router-outlet>
      </div>

    </main>
  </body>
</html>

// src/react-ji-tele-health/src/components/App/App.js
import React from "react";
import { Route, Switch } from "react-router-dom";
import { NavLink } from "react-router-dom";
import HomePage from "../HomePage";
import ClinicalNotes from "../ClinicalNotes";
import ClinicalNotesModify from "../ClinicalNotesModify";
import PatientModify from "../PatientModify";
import AboutPage from "../AboutPage";
import NotFoundPage from "../NotFoundPage";
import "./App.css";

function App() {
  return (
    <>
      <nav className="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a className="navbar-brand" href="#">
          Patient Manager
        </a>
        <button
          className="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarsExampleDefault"
          aria-controls="navbarsExampleDefault"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon"></span>
        </button>

        <div className="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul className="navbar-nav mr-auto">
            <li className="nav-item active">
              <NavLink className="nav-link" exact to="/">
                Home
              </NavLink>
            </li>
            <li className="nav-item">
              <NavLink className="nav-link" exact to="/about">
                About
              </NavLink>
            </li>
          </ul>
        </div>
      </nav>
      <main role="main" className="container">
        <div className="starter-template">
          <Switch>
            <Route path="/" exact component={HomePage} />
            <Route path="/notes/:id" component={ClinicalNotes} />
            <Route
              path="/note/modify/:id/:patientId"
              component={ClinicalNotesModify}
            />
            <Route path="/patient/:id" component={PatientModify} />
            <Route path="/about" component={AboutPage} />
            <Route component={NotFoundPage} />
          </Switch>
        </div>
      </main>
    </>
  );
}

export default App;
